// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: babylonlabs/babylon/v1beta1/babylon.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the x/babylon module.
type Params struct {
	// max_gas_begin_blocker defines the maximum gas that can be spent in a
	// contract sudo callback
	MaxGasBeginBlocker uint32 `protobuf:"varint,1,opt,name=max_gas_begin_blocker,json=maxGasBeginBlocker,proto3" json:"max_gas_begin_blocker,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eb75d1c9a41f85f, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// BSNContracts holds all four contract addresses for the Babylon module.
type BSNContracts struct {
	BabylonContract        string `protobuf:"bytes,1,opt,name=babylon_contract,json=babylonContract,proto3" json:"babylon_contract,omitempty"`
	BtcLightClientContract string `protobuf:"bytes,2,opt,name=btc_light_client_contract,json=btcLightClientContract,proto3" json:"btc_light_client_contract,omitempty"`
	BtcStakingContract     string `protobuf:"bytes,3,opt,name=btc_staking_contract,json=btcStakingContract,proto3" json:"btc_staking_contract,omitempty"`
	BtcFinalityContract    string `protobuf:"bytes,4,opt,name=btc_finality_contract,json=btcFinalityContract,proto3" json:"btc_finality_contract,omitempty"`
}

func (m *BSNContracts) Reset()         { *m = BSNContracts{} }
func (m *BSNContracts) String() string { return proto.CompactTextString(m) }
func (*BSNContracts) ProtoMessage()    {}
func (*BSNContracts) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eb75d1c9a41f85f, []int{1}
}
func (m *BSNContracts) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BSNContracts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BSNContracts.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BSNContracts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BSNContracts.Merge(m, src)
}
func (m *BSNContracts) XXX_Size() int {
	return m.Size()
}
func (m *BSNContracts) XXX_DiscardUnknown() {
	xxx_messageInfo_BSNContracts.DiscardUnknown(m)
}

var xxx_messageInfo_BSNContracts proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "babylonlabs.babylon.v1beta1.Params")
	proto.RegisterType((*BSNContracts)(nil), "babylonlabs.babylon.v1beta1.BSNContracts")
}

func init() {
	proto.RegisterFile("babylonlabs/babylon/v1beta1/babylon.proto", fileDescriptor_9eb75d1c9a41f85f)
}

var fileDescriptor_9eb75d1c9a41f85f = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x86, 0x93, 0xde, 0x52, 0xb8, 0xc3, 0xbd, 0xdc, 0x4b, 0x6c, 0xa5, 0xad, 0x30, 0x4a, 0x57,
	0xba, 0x68, 0x43, 0x11, 0x37, 0xee, 0x9a, 0x82, 0x82, 0x14, 0x91, 0x66, 0x21, 0xb8, 0x09, 0x33,
	0xd3, 0x38, 0x1d, 0x9a, 0x64, 0x4a, 0xe6, 0x28, 0xed, 0x5b, 0xf8, 0x08, 0x2e, 0x7d, 0x00, 0x9f,
	0xc0, 0x55, 0x97, 0xc5, 0x95, 0x4b, 0x4d, 0x37, 0x3e, 0x86, 0x24, 0x99, 0xb4, 0xdd, 0x75, 0x77,
	0xce, 0xfc, 0xe7, 0xfb, 0x66, 0x60, 0x0e, 0x3a, 0xa1, 0x84, 0xce, 0x03, 0x19, 0x05, 0x84, 0x2a,
	0x5b, 0xd7, 0xf6, 0x63, 0x97, 0xfa, 0x40, 0xba, 0x45, 0xdf, 0x99, 0xc6, 0x12, 0xa4, 0x75, 0xb0,
	0x35, 0xda, 0x29, 0x22, 0x3d, 0xda, 0xac, 0x72, 0xc9, 0x65, 0x36, 0x67, 0xa7, 0x55, 0x8e, 0x34,
	0x1b, 0x4c, 0xaa, 0x50, 0x2a, 0x2f, 0x0f, 0xf2, 0x26, 0x8f, 0x5a, 0x3d, 0x54, 0xb9, 0x21, 0x31,
	0x09, 0x95, 0xd5, 0x45, 0xb5, 0x90, 0xcc, 0x3c, 0x4e, 0x94, 0x47, 0x7d, 0x2e, 0x22, 0x8f, 0x06,
	0x92, 0x4d, 0xfc, 0xb8, 0x6e, 0x1e, 0x99, 0xc7, 0x7f, 0x87, 0x56, 0x48, 0x66, 0x97, 0x44, 0x39,
	0x69, 0xe4, 0xe4, 0xc9, 0x79, 0xf9, 0xfb, 0xf9, 0xd0, 0x6c, 0xbd, 0x95, 0xd0, 0x1f, 0xc7, 0xbd,
	0xee, 0xcb, 0x08, 0x62, 0xc2, 0x40, 0x59, 0x7d, 0xf4, 0x5f, 0xbf, 0xcb, 0x63, 0xfa, 0x30, 0x93,
	0xfc, 0x76, 0xea, 0xef, 0xaf, 0xed, 0xaa, 0xbe, 0xbf, 0x37, 0x1a, 0xc5, 0xbe, 0x52, 0x2e, 0xc4,
	0x22, 0xe2, 0xc3, 0x7f, 0x9a, 0x28, 0x2c, 0x96, 0x8b, 0x1a, 0x14, 0x98, 0x17, 0x08, 0x3e, 0x06,
	0x8f, 0x05, 0xc2, 0x8f, 0x60, 0x63, 0x2b, 0xed, 0xb0, 0xed, 0x53, 0x60, 0x83, 0x94, 0xec, 0x67,
	0xe0, 0x5a, 0x7a, 0x85, 0xaa, 0xa9, 0x54, 0x01, 0x99, 0x88, 0x88, 0x6f, 0x7c, 0xbf, 0x76, 0xf8,
	0x2c, 0x0a, 0xcc, 0xcd, 0xa1, 0xb5, 0x6b, 0x80, 0x6a, 0xa9, 0xeb, 0x5e, 0x44, 0x24, 0x10, 0x30,
	0xdf, 0xc8, 0xca, 0x3b, 0x64, 0x7b, 0x14, 0xd8, 0x85, 0xa6, 0x0a, 0x9b, 0x73, 0xbb, 0xf8, 0xc2,
	0xc6, 0x4b, 0x82, 0x8d, 0x45, 0x82, 0xcd, 0x65, 0x82, 0xcd, 0xcf, 0x04, 0x9b, 0x4f, 0x2b, 0x6c,
	0x2c, 0x57, 0xd8, 0xf8, 0x58, 0x61, 0xe3, 0xee, 0x8c, 0x0b, 0x18, 0x3f, 0xd0, 0x0e, 0x93, 0xa1,
	0xbd, 0xb5, 0x02, 0x6d, 0x21, 0x8b, 0xb6, 0xad, 0x46, 0x13, 0x7b, 0xb6, 0x5e, 0x1f, 0x98, 0x4f,
	0x7d, 0x45, 0x2b, 0xd9, 0x3f, 0x9f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x41, 0x3a, 0x0c, 0xfd,
	0x62, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MaxGasBeginBlocker != that1.MaxGasBeginBlocker {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxGasBeginBlocker != 0 {
		i = encodeVarintBabylon(dAtA, i, uint64(m.MaxGasBeginBlocker))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BSNContracts) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BSNContracts) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BSNContracts) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BtcFinalityContract) > 0 {
		i -= len(m.BtcFinalityContract)
		copy(dAtA[i:], m.BtcFinalityContract)
		i = encodeVarintBabylon(dAtA, i, uint64(len(m.BtcFinalityContract)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.BtcStakingContract) > 0 {
		i -= len(m.BtcStakingContract)
		copy(dAtA[i:], m.BtcStakingContract)
		i = encodeVarintBabylon(dAtA, i, uint64(len(m.BtcStakingContract)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BtcLightClientContract) > 0 {
		i -= len(m.BtcLightClientContract)
		copy(dAtA[i:], m.BtcLightClientContract)
		i = encodeVarintBabylon(dAtA, i, uint64(len(m.BtcLightClientContract)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BabylonContract) > 0 {
		i -= len(m.BabylonContract)
		copy(dAtA[i:], m.BabylonContract)
		i = encodeVarintBabylon(dAtA, i, uint64(len(m.BabylonContract)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBabylon(dAtA []byte, offset int, v uint64) int {
	offset -= sovBabylon(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxGasBeginBlocker != 0 {
		n += 1 + sovBabylon(uint64(m.MaxGasBeginBlocker))
	}
	return n
}

func (m *BSNContracts) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BabylonContract)
	if l > 0 {
		n += 1 + l + sovBabylon(uint64(l))
	}
	l = len(m.BtcLightClientContract)
	if l > 0 {
		n += 1 + l + sovBabylon(uint64(l))
	}
	l = len(m.BtcStakingContract)
	if l > 0 {
		n += 1 + l + sovBabylon(uint64(l))
	}
	l = len(m.BtcFinalityContract)
	if l > 0 {
		n += 1 + l + sovBabylon(uint64(l))
	}
	return n
}

func sovBabylon(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBabylon(x uint64) (n int) {
	return sovBabylon(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBabylon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGasBeginBlocker", wireType)
			}
			m.MaxGasBeginBlocker = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxGasBeginBlocker |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBabylon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBabylon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BSNContracts) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBabylon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BSNContracts: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BSNContracts: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BabylonContract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBabylon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBabylon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BabylonContract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcLightClientContract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBabylon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBabylon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcLightClientContract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcStakingContract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBabylon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBabylon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcStakingContract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcFinalityContract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBabylon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBabylon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcFinalityContract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBabylon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBabylon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBabylon(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBabylon
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBabylon
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBabylon
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBabylon
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBabylon        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBabylon          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBabylon = fmt.Errorf("proto: unexpected end of group")
)
