// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: babylonlabs/babylon/v1beta1/babylon.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the x/babylon module.
type Params struct {
	// babylon_contract_address is the address of the Babylon contract
	BabylonContractAddress string `protobuf:"bytes,1,opt,name=babylon_contract_address,json=babylonContractAddress,proto3" json:"babylon_contract_address,omitempty"`
	// btc_staking_contract_address is the address of the BTC staking contract
	BtcStakingContractAddress string `protobuf:"bytes,2,opt,name=btc_staking_contract_address,json=btcStakingContractAddress,proto3" json:"btc_staking_contract_address,omitempty"`
	// btc_finality_contract_address is the address of the BTC finality contract
	BtcFinalityContractAddress string `protobuf:"bytes,3,opt,name=btc_finality_contract_address,json=btcFinalityContractAddress,proto3" json:"btc_finality_contract_address,omitempty"`
	// max_gas_begin_blocker defines the maximum gas that can be spent in a
	// contract sudo callback
	MaxGasBeginBlocker uint32 `protobuf:"varint,4,opt,name=max_gas_begin_blocker,json=maxGasBeginBlocker,proto3" json:"max_gas_begin_blocker,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eb75d1c9a41f85f, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "babylonlabs.babylon.v1beta1.Params")
}

func init() {
	proto.RegisterFile("babylonlabs/babylon/v1beta1/babylon.proto", fileDescriptor_9eb75d1c9a41f85f)
}

var fileDescriptor_9eb75d1c9a41f85f = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xb1, 0x4e, 0x32, 0x41,
	0x14, 0x85, 0x77, 0xf8, 0x09, 0xc9, 0xbf, 0x89, 0xcd, 0x06, 0xcd, 0x82, 0x3a, 0x12, 0x2b, 0x2c,
	0x60, 0x43, 0x8c, 0x8d, 0x9d, 0x6b, 0xa2, 0xad, 0x81, 0xc2, 0xa8, 0xc5, 0xe4, 0xce, 0xb0, 0x8e,
	0x13, 0x76, 0x77, 0xc8, 0xce, 0x68, 0xe0, 0x2d, 0x7c, 0x04, 0x4b, 0x1f, 0xc0, 0x87, 0xa0, 0x31,
	0x21, 0x56, 0x96, 0xba, 0x34, 0x3e, 0x86, 0x81, 0x99, 0x35, 0x04, 0x0a, 0xba, 0x7b, 0xee, 0x39,
	0xe7, 0x6b, 0xee, 0x75, 0x8f, 0x28, 0xd0, 0x71, 0x2c, 0xd3, 0x18, 0xa8, 0x0a, 0xec, 0x1c, 0x3c,
	0x75, 0x68, 0xa4, 0xa1, 0x53, 0xe8, 0xf6, 0x30, 0x93, 0x5a, 0x7a, 0xbb, 0x4b, 0xd1, 0x76, 0x61,
	0xd9, 0x68, 0xbd, 0xc6, 0xa4, 0x4a, 0xa4, 0x22, 0x8b, 0x68, 0x60, 0x84, 0xe9, 0xd5, 0xab, 0x5c,
	0x72, 0x69, 0xf6, 0xf3, 0xc9, 0x6c, 0x0f, 0xdf, 0x4b, 0x6e, 0xe5, 0x0a, 0x32, 0x48, 0x94, 0xd7,
	0x75, 0x7d, 0x8b, 0x23, 0x4c, 0xa6, 0x3a, 0x03, 0xa6, 0x09, 0xf4, 0xfb, 0x59, 0xa4, 0x94, 0x8f,
	0x1a, 0xa8, 0xf9, 0x3f, 0xf4, 0x3f, 0xde, 0x5a, 0x55, 0x0b, 0x3d, 0x33, 0x4e, 0x4f, 0x67, 0x22,
	0xe5, 0xdd, 0x1d, 0xdb, 0x3c, 0xb7, 0x45, 0xeb, 0x7a, 0x37, 0xee, 0x1e, 0xd5, 0x8c, 0x28, 0x0d,
	0x03, 0x91, 0xf2, 0x75, 0x6e, 0x69, 0x03, 0xb7, 0x46, 0x35, 0xeb, 0x99, 0xf2, 0x2a, 0xfa, 0xce,
	0xdd, 0x9f, 0xa3, 0xef, 0x45, 0x0a, 0xb1, 0xd0, 0xe3, 0x75, 0xf6, 0xbf, 0x0d, 0xec, 0x3a, 0xd5,
	0xec, 0xc2, 0xb6, 0x57, 0xe1, 0x1d, 0x77, 0x3b, 0x81, 0x11, 0xe1, 0xa0, 0x08, 0x8d, 0xb8, 0x48,
	0x09, 0x8d, 0x25, 0x1b, 0x44, 0x99, 0x5f, 0x6e, 0xa0, 0xe6, 0x56, 0xd7, 0x4b, 0x60, 0x74, 0x09,
	0x2a, 0x9c, 0x5b, 0xa1, 0x71, 0x4e, 0xcb, 0x3f, 0x2f, 0x07, 0x28, 0xbc, 0x9e, 0x7c, 0x63, 0xe7,
	0x35, 0xc7, 0xce, 0x24, 0xc7, 0x68, 0x9a, 0x63, 0xf4, 0x95, 0x63, 0xf4, 0x3c, 0xc3, 0xce, 0x74,
	0x86, 0x9d, 0xcf, 0x19, 0x76, 0x6e, 0x4f, 0xb8, 0xd0, 0x0f, 0x8f, 0xb4, 0xcd, 0x64, 0x12, 0x2c,
	0x9d, 0xb2, 0x25, 0x64, 0x21, 0x5b, 0xaa, 0x3f, 0x08, 0x46, 0x7f, 0x6f, 0xa0, 0xc7, 0xc3, 0x48,
	0xd1, 0xca, 0xe2, 0x5e, 0xc7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xe1, 0x4c, 0x30, 0x2a,
	0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.BabylonContractAddress != that1.BabylonContractAddress {
		return false
	}
	if this.BtcStakingContractAddress != that1.BtcStakingContractAddress {
		return false
	}
	if this.BtcFinalityContractAddress != that1.BtcFinalityContractAddress {
		return false
	}
	if this.MaxGasBeginBlocker != that1.MaxGasBeginBlocker {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxGasBeginBlocker != 0 {
		i = encodeVarintBabylon(dAtA, i, uint64(m.MaxGasBeginBlocker))
		i--
		dAtA[i] = 0x20
	}
	if len(m.BtcFinalityContractAddress) > 0 {
		i -= len(m.BtcFinalityContractAddress)
		copy(dAtA[i:], m.BtcFinalityContractAddress)
		i = encodeVarintBabylon(dAtA, i, uint64(len(m.BtcFinalityContractAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BtcStakingContractAddress) > 0 {
		i -= len(m.BtcStakingContractAddress)
		copy(dAtA[i:], m.BtcStakingContractAddress)
		i = encodeVarintBabylon(dAtA, i, uint64(len(m.BtcStakingContractAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BabylonContractAddress) > 0 {
		i -= len(m.BabylonContractAddress)
		copy(dAtA[i:], m.BabylonContractAddress)
		i = encodeVarintBabylon(dAtA, i, uint64(len(m.BabylonContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBabylon(dAtA []byte, offset int, v uint64) int {
	offset -= sovBabylon(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BabylonContractAddress)
	if l > 0 {
		n += 1 + l + sovBabylon(uint64(l))
	}
	l = len(m.BtcStakingContractAddress)
	if l > 0 {
		n += 1 + l + sovBabylon(uint64(l))
	}
	l = len(m.BtcFinalityContractAddress)
	if l > 0 {
		n += 1 + l + sovBabylon(uint64(l))
	}
	if m.MaxGasBeginBlocker != 0 {
		n += 1 + sovBabylon(uint64(m.MaxGasBeginBlocker))
	}
	return n
}

func sovBabylon(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBabylon(x uint64) (n int) {
	return sovBabylon(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBabylon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BabylonContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBabylon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBabylon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BabylonContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcStakingContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBabylon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBabylon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcStakingContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcFinalityContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBabylon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBabylon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcFinalityContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGasBeginBlocker", wireType)
			}
			m.MaxGasBeginBlocker = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxGasBeginBlocker |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBabylon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBabylon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBabylon(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBabylon
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBabylon
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBabylon
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBabylon
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBabylon        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBabylon          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBabylon = fmt.Errorf("proto: unexpected end of group")
)
