// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: babylonlabs/babylon/v1beta1/babylon.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the x/babylon module.
type Params struct {
	// max_gas_begin_blocker defines the maximum gas that can be spent in a
	// contract sudo callback for begin blocker
	MaxGasBeginBlocker uint32 `protobuf:"varint,1,opt,name=max_gas_begin_blocker,json=maxGasBeginBlocker,proto3" json:"max_gas_begin_blocker,omitempty"`
	// max_gas_end_blocker defines the maximum gas that can be spent in a
	// contract sudo callback for end blocker
	MaxGasEndBlocker uint32 `protobuf:"varint,2,opt,name=max_gas_end_blocker,json=maxGasEndBlocker,proto3" json:"max_gas_end_blocker,omitempty"`
	// btc_staking_portion is the portion of rewards that goes to Finality
	// Providers/delegations NOTE: the portion of each Finality
	// Provider/delegation is calculated by using its voting power and finality
	// provider's commission
	BtcStakingPortion cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=btc_staking_portion,json=btcStakingPortion,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"btc_staking_portion"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eb75d1c9a41f85f, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// BSNContracts holds all four contract addresses for the Babylon module.
type BSNContracts struct {
	BabylonContract        string `protobuf:"bytes,1,opt,name=babylon_contract,json=babylonContract,proto3" json:"babylon_contract,omitempty"`
	BtcLightClientContract string `protobuf:"bytes,2,opt,name=btc_light_client_contract,json=btcLightClientContract,proto3" json:"btc_light_client_contract,omitempty"`
	BtcStakingContract     string `protobuf:"bytes,3,opt,name=btc_staking_contract,json=btcStakingContract,proto3" json:"btc_staking_contract,omitempty"`
	BtcFinalityContract    string `protobuf:"bytes,4,opt,name=btc_finality_contract,json=btcFinalityContract,proto3" json:"btc_finality_contract,omitempty"`
}

func (m *BSNContracts) Reset()         { *m = BSNContracts{} }
func (m *BSNContracts) String() string { return proto.CompactTextString(m) }
func (*BSNContracts) ProtoMessage()    {}
func (*BSNContracts) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eb75d1c9a41f85f, []int{1}
}
func (m *BSNContracts) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BSNContracts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BSNContracts.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BSNContracts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BSNContracts.Merge(m, src)
}
func (m *BSNContracts) XXX_Size() int {
	return m.Size()
}
func (m *BSNContracts) XXX_DiscardUnknown() {
	xxx_messageInfo_BSNContracts.DiscardUnknown(m)
}

var xxx_messageInfo_BSNContracts proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "babylonlabs.babylon.v1beta1.Params")
	proto.RegisterType((*BSNContracts)(nil), "babylonlabs.babylon.v1beta1.BSNContracts")
}

func init() {
	proto.RegisterFile("babylonlabs/babylon/v1beta1/babylon.proto", fileDescriptor_9eb75d1c9a41f85f)
}

var fileDescriptor_9eb75d1c9a41f85f = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0xc7, 0x93, 0x6e, 0x9a, 0x34, 0x0b, 0xc4, 0xc8, 0x3a, 0xd4, 0x6d, 0x52, 0x3a, 0xed, 0x34,
	0x0e, 0x49, 0x54, 0x21, 0x2e, 0xdc, 0x48, 0x07, 0x48, 0xa8, 0x42, 0x53, 0x7b, 0x40, 0xe2, 0x12,
	0xd9, 0x8e, 0x71, 0xad, 0x26, 0x76, 0x15, 0x7f, 0xa0, 0xf6, 0x2d, 0x78, 0x04, 0x8e, 0x3c, 0xc0,
	0x9e, 0x80, 0x53, 0x8f, 0xd3, 0xb8, 0x20, 0x0e, 0x15, 0xb4, 0x17, 0x1e, 0x63, 0x4a, 0xec, 0xa4,
	0xbd, 0xf5, 0xe6, 0x2f, 0xff, 0xef, 0xf7, 0xd3, 0x67, 0xe7, 0x43, 0xcf, 0x09, 0x26, 0xf3, 0x4c,
	0xc9, 0x0c, 0x13, 0x1d, 0xd9, 0x73, 0xf4, 0xb5, 0x47, 0x18, 0xe0, 0x5e, 0x5d, 0x87, 0xd3, 0x42,
	0x81, 0xf2, 0xce, 0xb7, 0x5a, 0xc3, 0x3a, 0xb2, 0xad, 0x67, 0x6d, 0xae, 0xb8, 0xaa, 0xfa, 0xa2,
	0xf2, 0x64, 0x90, 0xb3, 0x53, 0xaa, 0x74, 0xae, 0x74, 0x62, 0x02, 0x53, 0x98, 0xe8, 0xf2, 0x97,
	0x8b, 0x0e, 0x6e, 0x70, 0x81, 0x73, 0xed, 0xf5, 0xd0, 0x49, 0x8e, 0x67, 0x09, 0xc7, 0x3a, 0x21,
	0x8c, 0x0b, 0x99, 0x90, 0x4c, 0xd1, 0x09, 0x2b, 0x3a, 0xee, 0x85, 0x7b, 0xf5, 0x78, 0xe8, 0xe5,
	0x78, 0xf6, 0x0e, 0xeb, 0xb8, 0x8c, 0x62, 0x93, 0x78, 0x01, 0x3a, 0xae, 0x11, 0x26, 0xd3, 0x06,
	0x68, 0x55, 0xc0, 0x91, 0x01, 0xde, 0xc8, 0xb4, 0x6e, 0xc7, 0xe8, 0x98, 0x00, 0x4d, 0x34, 0xe0,
	0x89, 0x90, 0x3c, 0x99, 0xaa, 0x02, 0x84, 0x92, 0x9d, 0xbd, 0x0b, 0xf7, 0xea, 0x30, 0xee, 0x2d,
	0x96, 0x5d, 0xe7, 0xcf, 0xb2, 0x7b, 0x6e, 0xe6, 0xd3, 0xe9, 0x24, 0x14, 0x2a, 0xca, 0x31, 0x8c,
	0xc3, 0x01, 0xe3, 0x98, 0xce, 0xaf, 0x19, 0xbd, 0xbf, 0x0d, 0x90, 0x1d, 0xff, 0x9a, 0xd1, 0xe1,
	0x53, 0x02, 0x74, 0x64, 0x64, 0x37, 0xc6, 0xf5, 0x6a, 0xff, 0xff, 0xf7, 0xae, 0x7b, 0xf9, 0xb3,
	0x85, 0x1e, 0xc5, 0xa3, 0x0f, 0x7d, 0x25, 0xa1, 0xc0, 0x14, 0xb4, 0xd7, 0x47, 0x47, 0xf6, 0xa9,
	0x12, 0x6a, 0x3f, 0x56, 0xd7, 0x3a, 0x8c, 0x3b, 0xf7, 0xb7, 0x41, 0xdb, 0x3a, 0x5f, 0xa7, 0x69,
	0xc1, 0xb4, 0x1e, 0x41, 0x21, 0x24, 0x1f, 0x3e, 0xb1, 0x44, 0x6d, 0xf1, 0x46, 0xe8, 0xb4, 0x1c,
	0x3f, 0x13, 0x7c, 0x0c, 0x09, 0xcd, 0x04, 0x93, 0xb0, 0xb1, 0xb5, 0x76, 0xd8, 0x9e, 0x11, 0xa0,
	0x83, 0x92, 0xec, 0x57, 0x60, 0x23, 0x7d, 0x8f, 0xda, 0xdb, 0x6f, 0xd2, 0xf8, 0xf6, 0x76, 0xf8,
	0xbc, 0xcd, 0xdd, 0x1b, 0xd7, 0x00, 0x9d, 0x94, 0xae, 0xcf, 0x42, 0xe2, 0x4c, 0xc0, 0x7c, 0x23,
	0xdb, 0xdf, 0x21, 0x2b, 0x7f, 0xcb, 0x5b, 0x4b, 0xd5, 0xb6, 0xf8, 0xe3, 0xe2, 0x9f, 0xef, 0xfc,
	0x58, 0xf9, 0xce, 0x62, 0xe5, 0xbb, 0x77, 0x2b, 0xdf, 0xfd, 0xbb, 0xf2, 0xdd, 0x6f, 0x6b, 0xdf,
	0xb9, 0x5b, 0xfb, 0xce, 0xef, 0xb5, 0xef, 0x7c, 0x7a, 0xc9, 0x05, 0x8c, 0xbf, 0x90, 0x90, 0xaa,
	0x3c, 0xda, 0xda, 0xca, 0x40, 0xa8, 0xba, 0x0c, 0x74, 0x3a, 0x89, 0x66, 0xcd, 0x46, 0xc3, 0x7c,
	0xca, 0x34, 0x39, 0xa8, 0x56, 0xef, 0xc5, 0x43, 0x00, 0x00, 0x00, 0xff, 0xff, 0x40, 0x78, 0x83,
	0x3b, 0xf5, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MaxGasBeginBlocker != that1.MaxGasBeginBlocker {
		return false
	}
	if this.MaxGasEndBlocker != that1.MaxGasEndBlocker {
		return false
	}
	if !this.BtcStakingPortion.Equal(that1.BtcStakingPortion) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.BtcStakingPortion.Size()
		i -= size
		if _, err := m.BtcStakingPortion.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintBabylon(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.MaxGasEndBlocker != 0 {
		i = encodeVarintBabylon(dAtA, i, uint64(m.MaxGasEndBlocker))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxGasBeginBlocker != 0 {
		i = encodeVarintBabylon(dAtA, i, uint64(m.MaxGasBeginBlocker))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BSNContracts) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BSNContracts) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BSNContracts) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BtcFinalityContract) > 0 {
		i -= len(m.BtcFinalityContract)
		copy(dAtA[i:], m.BtcFinalityContract)
		i = encodeVarintBabylon(dAtA, i, uint64(len(m.BtcFinalityContract)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.BtcStakingContract) > 0 {
		i -= len(m.BtcStakingContract)
		copy(dAtA[i:], m.BtcStakingContract)
		i = encodeVarintBabylon(dAtA, i, uint64(len(m.BtcStakingContract)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BtcLightClientContract) > 0 {
		i -= len(m.BtcLightClientContract)
		copy(dAtA[i:], m.BtcLightClientContract)
		i = encodeVarintBabylon(dAtA, i, uint64(len(m.BtcLightClientContract)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BabylonContract) > 0 {
		i -= len(m.BabylonContract)
		copy(dAtA[i:], m.BabylonContract)
		i = encodeVarintBabylon(dAtA, i, uint64(len(m.BabylonContract)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBabylon(dAtA []byte, offset int, v uint64) int {
	offset -= sovBabylon(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxGasBeginBlocker != 0 {
		n += 1 + sovBabylon(uint64(m.MaxGasBeginBlocker))
	}
	if m.MaxGasEndBlocker != 0 {
		n += 1 + sovBabylon(uint64(m.MaxGasEndBlocker))
	}
	l = m.BtcStakingPortion.Size()
	n += 1 + l + sovBabylon(uint64(l))
	return n
}

func (m *BSNContracts) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BabylonContract)
	if l > 0 {
		n += 1 + l + sovBabylon(uint64(l))
	}
	l = len(m.BtcLightClientContract)
	if l > 0 {
		n += 1 + l + sovBabylon(uint64(l))
	}
	l = len(m.BtcStakingContract)
	if l > 0 {
		n += 1 + l + sovBabylon(uint64(l))
	}
	l = len(m.BtcFinalityContract)
	if l > 0 {
		n += 1 + l + sovBabylon(uint64(l))
	}
	return n
}

func sovBabylon(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBabylon(x uint64) (n int) {
	return sovBabylon(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBabylon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGasBeginBlocker", wireType)
			}
			m.MaxGasBeginBlocker = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxGasBeginBlocker |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGasEndBlocker", wireType)
			}
			m.MaxGasEndBlocker = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxGasEndBlocker |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcStakingPortion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBabylon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBabylon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BtcStakingPortion.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBabylon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBabylon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BSNContracts) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBabylon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BSNContracts: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BSNContracts: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BabylonContract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBabylon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBabylon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BabylonContract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcLightClientContract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBabylon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBabylon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcLightClientContract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcStakingContract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBabylon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBabylon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcStakingContract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcFinalityContract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBabylon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBabylon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcFinalityContract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBabylon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBabylon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBabylon(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBabylon
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBabylon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBabylon
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBabylon
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBabylon
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBabylon        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBabylon          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBabylon = fmt.Errorf("proto: unexpected end of group")
)
