// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: babylonlabs/babylon/v1beta1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the x/babylon module.
type Params struct {
	// babylon_contract_code_id is the code ID of the Babylon contract
	BabylonContractCodeId uint64 `protobuf:"varint,1,opt,name=babylon_contract_code_id,json=babylonContractCodeId,proto3" json:"babylon_contract_code_id,omitempty"`
	// btc_staking_contract_code_id is the code ID of the BTC staking contract
	BtcStakingContractCodeId uint64 `protobuf:"varint,2,opt,name=btc_staking_contract_code_id,json=btcStakingContractCodeId,proto3" json:"btc_staking_contract_code_id,omitempty"`
	// btc_finality_contract_code_id is the code ID of the BTC finality contract
	BtcFinalityContractCodeId uint64 `protobuf:"varint,3,opt,name=btc_finality_contract_code_id,json=btcFinalityContractCodeId,proto3" json:"btc_finality_contract_code_id,omitempty"`
	// babylon_contract_address is the address of the Babylon contract
	BabylonContractAddress string `protobuf:"bytes,4,opt,name=babylon_contract_address,json=babylonContractAddress,proto3" json:"babylon_contract_address,omitempty"`
	// btc_staking_contract_address is the address of the BTC staking contract
	BtcStakingContractAddress string `protobuf:"bytes,5,opt,name=btc_staking_contract_address,json=btcStakingContractAddress,proto3" json:"btc_staking_contract_address,omitempty"`
	// btc_finality_contract_address is the address of the BTC finality contract
	BtcFinalityContractAddress string `protobuf:"bytes,6,opt,name=btc_finality_contract_address,json=btcFinalityContractAddress,proto3" json:"btc_finality_contract_address,omitempty"`
	// max_gas_begin_blocker defines the maximum gas that can be spent in a
	// contract sudo callback
	MaxGasBeginBlocker uint32 `protobuf:"varint,7,opt,name=max_gas_begin_blocker,json=maxGasBeginBlocker,proto3" json:"max_gas_begin_blocker,omitempty"`
	// btc_staking_portion is the portion of rewards that goes to Finality
	// Providers/delegations NOTE: the portion of each Finality
	// Provider/delegation is calculated by using its voting power and finality
	// provider's commission
	BtcStakingPortion cosmossdk_io_math.LegacyDec `protobuf:"bytes,8,opt,name=btc_staking_portion,json=btcStakingPortion,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"btc_staking_portion"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c87ccbf1b8b8312, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBabylonContractCodeId() uint64 {
	if m != nil {
		return m.BabylonContractCodeId
	}
	return 0
}

func (m *Params) GetBtcStakingContractCodeId() uint64 {
	if m != nil {
		return m.BtcStakingContractCodeId
	}
	return 0
}

func (m *Params) GetBtcFinalityContractCodeId() uint64 {
	if m != nil {
		return m.BtcFinalityContractCodeId
	}
	return 0
}

func (m *Params) GetBabylonContractAddress() string {
	if m != nil {
		return m.BabylonContractAddress
	}
	return ""
}

func (m *Params) GetBtcStakingContractAddress() string {
	if m != nil {
		return m.BtcStakingContractAddress
	}
	return ""
}

func (m *Params) GetBtcFinalityContractAddress() string {
	if m != nil {
		return m.BtcFinalityContractAddress
	}
	return ""
}

func (m *Params) GetMaxGasBeginBlocker() uint32 {
	if m != nil {
		return m.MaxGasBeginBlocker
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "babylonlabs.babylon.v1beta1.Params")
}

func init() {
	proto.RegisterFile("babylonlabs/babylon/v1beta1/params.proto", fileDescriptor_2c87ccbf1b8b8312)
}

var fileDescriptor_2c87ccbf1b8b8312 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x4f, 0x6b, 0x13, 0x41,
	0x18, 0xc6, 0x77, 0x35, 0xc6, 0xba, 0xe0, 0xc1, 0xb5, 0x95, 0x4d, 0xaa, 0x9b, 0xe0, 0x29, 0x97,
	0xec, 0x12, 0x44, 0x04, 0x0f, 0xa2, 0x69, 0x51, 0x04, 0xc1, 0xb2, 0x3d, 0xa9, 0x87, 0xe1, 0x9d,
	0x3f, 0x4e, 0x87, 0x64, 0xf7, 0x0d, 0x3b, 0xa3, 0x24, 0xdf, 0xc2, 0xa3, 0xc7, 0x7e, 0x88, 0x7e,
	0x88, 0x1e, 0x4b, 0x4f, 0xe2, 0xa1, 0x48, 0x72, 0xf1, 0xe6, 0x57, 0x90, 0xec, 0xcc, 0x6a, 0x48,
	0x5a, 0x7a, 0x7b, 0x87, 0xe7, 0x79, 0x7e, 0xbc, 0xcf, 0xf2, 0x6e, 0xd0, 0xa3, 0x40, 0x67, 0x63,
	0x2c, 0xc6, 0x40, 0x75, 0xea, 0xe6, 0xf4, 0xeb, 0x80, 0x0a, 0x03, 0x83, 0x74, 0x02, 0x25, 0xe4,
	0x3a, 0x99, 0x94, 0x68, 0x30, 0xdc, 0x5d, 0x71, 0x26, 0x6e, 0x4e, 0x9c, 0xb3, 0xbd, 0x2d, 0x51,
	0x62, 0xe5, 0x4b, 0x97, 0x93, 0x8d, 0xb4, 0x5b, 0x0c, 0x75, 0x8e, 0x9a, 0x58, 0xc1, 0x3e, 0xac,
	0xf4, 0xf8, 0x4f, 0x23, 0x68, 0x1e, 0x54, 0xf8, 0xf0, 0x59, 0x10, 0x39, 0x1c, 0x61, 0x58, 0x98,
	0x12, 0x98, 0x21, 0x0c, 0xb9, 0x20, 0x8a, 0x47, 0x7e, 0xd7, 0xef, 0x35, 0xb2, 0x1d, 0xa7, 0xef,
	0x39, 0x79, 0x0f, 0xb9, 0x78, 0xcb, 0xc3, 0x17, 0xc1, 0x43, 0x6a, 0x18, 0xd1, 0x06, 0x46, 0xaa,
	0x90, 0x9b, 0xe1, 0x1b, 0x55, 0x38, 0xa2, 0x86, 0x1d, 0x5a, 0xcb, 0x5a, 0xfe, 0x65, 0xf0, 0x68,
	0x99, 0xff, 0xac, 0x0a, 0x18, 0x2b, 0x33, 0xdb, 0x04, 0xdc, 0xac, 0x00, 0x2d, 0x6a, 0xd8, 0x6b,
	0xe7, 0x59, 0x23, 0x64, 0x97, 0xac, 0x0e, 0x9c, 0x97, 0x42, 0xeb, 0xa8, 0xd1, 0xf5, 0x7b, 0x77,
	0x86, 0xd1, 0xf9, 0x49, 0x7f, 0xdb, 0x35, 0x7f, 0x65, 0x95, 0x43, 0x53, 0xaa, 0x42, 0x66, 0x0f,
	0xd6, 0x4a, 0x39, 0x35, 0xfc, 0x70, 0x45, 0xab, 0x9a, 0x7b, 0xeb, 0x1a, 0x6e, 0x6b, 0xb3, 0x6f,
	0x8d, 0xfe, 0x74, 0x55, 0xe1, 0x9a, 0xdd, 0xbc, 0x86, 0xdd, 0xbe, 0xe4, 0x53, 0xd4, 0xf0, 0x41,
	0xb0, 0x93, 0xc3, 0x94, 0x48, 0xd0, 0x84, 0x0a, 0xa9, 0x0a, 0x42, 0xc7, 0xc8, 0x46, 0xa2, 0x8c,
	0x6e, 0x77, 0xfd, 0xde, 0xdd, 0x2c, 0xcc, 0x61, 0xfa, 0x06, 0xf4, 0x70, 0x29, 0x0d, 0xad, 0x12,
	0x42, 0x70, 0x7f, 0xb5, 0xea, 0x04, 0x4b, 0xa3, 0xb0, 0x88, 0xb6, 0xaa, 0x2d, 0x06, 0xa7, 0x17,
	0x1d, 0xef, 0xe7, 0x45, 0x67, 0xd7, 0x6e, 0xa2, 0xf9, 0x28, 0x51, 0x98, 0xe6, 0x60, 0x8e, 0x92,
	0x77, 0x42, 0x02, 0x9b, 0xed, 0x0b, 0x76, 0x7e, 0xd2, 0x0f, 0xdc, 0xa2, 0xfb, 0x82, 0x65, 0xf7,
	0xfe, 0x57, 0x3f, 0xb0, 0xac, 0xe7, 0x5b, 0xdf, 0x8f, 0x3b, 0xde, 0xef, 0xe3, 0x8e, 0x3f, 0x7c,
	0x7f, 0x3a, 0x8f, 0xfd, 0xb3, 0x79, 0xec, 0xff, 0x9a, 0xc7, 0xfe, 0xb7, 0x45, 0xec, 0x9d, 0x2d,
	0x62, 0xef, 0xc7, 0x22, 0xf6, 0x3e, 0x3e, 0x95, 0xca, 0x1c, 0x7d, 0xa1, 0x09, 0xc3, 0x3c, 0x5d,
	0x39, 0xf2, 0xbe, 0xc2, 0xfa, 0xd9, 0xd7, 0x7c, 0x94, 0x4e, 0xff, 0xfd, 0x1f, 0x66, 0x36, 0x11,
	0x9a, 0x36, 0xab, 0x4b, 0x7e, 0xf2, 0x37, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x1b, 0x62, 0xcd, 0x43,
	0x03, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.BabylonContractCodeId != that1.BabylonContractCodeId {
		return false
	}
	if this.BtcStakingContractCodeId != that1.BtcStakingContractCodeId {
		return false
	}
	if this.BtcFinalityContractCodeId != that1.BtcFinalityContractCodeId {
		return false
	}
	if this.BabylonContractAddress != that1.BabylonContractAddress {
		return false
	}
	if this.BtcStakingContractAddress != that1.BtcStakingContractAddress {
		return false
	}
	if this.BtcFinalityContractAddress != that1.BtcFinalityContractAddress {
		return false
	}
	if this.MaxGasBeginBlocker != that1.MaxGasBeginBlocker {
		return false
	}
	if !this.BtcStakingPortion.Equal(that1.BtcStakingPortion) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.BtcStakingPortion.Size()
		i -= size
		if _, err := m.BtcStakingPortion.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if m.MaxGasBeginBlocker != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxGasBeginBlocker))
		i--
		dAtA[i] = 0x38
	}
	if len(m.BtcFinalityContractAddress) > 0 {
		i -= len(m.BtcFinalityContractAddress)
		copy(dAtA[i:], m.BtcFinalityContractAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.BtcFinalityContractAddress)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.BtcStakingContractAddress) > 0 {
		i -= len(m.BtcStakingContractAddress)
		copy(dAtA[i:], m.BtcStakingContractAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.BtcStakingContractAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.BabylonContractAddress) > 0 {
		i -= len(m.BabylonContractAddress)
		copy(dAtA[i:], m.BabylonContractAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.BabylonContractAddress)))
		i--
		dAtA[i] = 0x22
	}
	if m.BtcFinalityContractCodeId != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BtcFinalityContractCodeId))
		i--
		dAtA[i] = 0x18
	}
	if m.BtcStakingContractCodeId != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BtcStakingContractCodeId))
		i--
		dAtA[i] = 0x10
	}
	if m.BabylonContractCodeId != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BabylonContractCodeId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BabylonContractCodeId != 0 {
		n += 1 + sovParams(uint64(m.BabylonContractCodeId))
	}
	if m.BtcStakingContractCodeId != 0 {
		n += 1 + sovParams(uint64(m.BtcStakingContractCodeId))
	}
	if m.BtcFinalityContractCodeId != 0 {
		n += 1 + sovParams(uint64(m.BtcFinalityContractCodeId))
	}
	l = len(m.BabylonContractAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.BtcStakingContractAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.BtcFinalityContractAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.MaxGasBeginBlocker != 0 {
		n += 1 + sovParams(uint64(m.MaxGasBeginBlocker))
	}
	l = m.BtcStakingPortion.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BabylonContractCodeId", wireType)
			}
			m.BabylonContractCodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BabylonContractCodeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcStakingContractCodeId", wireType)
			}
			m.BtcStakingContractCodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BtcStakingContractCodeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcFinalityContractCodeId", wireType)
			}
			m.BtcFinalityContractCodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BtcFinalityContractCodeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BabylonContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BabylonContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcStakingContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcStakingContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcFinalityContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcFinalityContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGasBeginBlocker", wireType)
			}
			m.MaxGasBeginBlocker = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxGasBeginBlocker |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcStakingPortion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BtcStakingPortion.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
