name: ci

on:
  push:
    branches:
    - '**'

permissions:
  contents: read

jobs:
  check-no-babylon-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2 https://github.com/actions/checkout/releases/tag/v6.0.2
      - name: Check no babylon dependencies in demo/ and x/
        run: ./scripts/check-no-babylon-deps.sh

  test:
    needs: ["check-no-babylon-deps"]
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@5d014a155c08d56a1b5673d049f2b4e7d4427825 # v0.19.0 https://github.com/babylonlabs-io/.github/releases/tag/v0.19.0
    with:
     run-unit-tests: true

  docker_pipeline:
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@5d014a155c08d56a1b5673d049f2b4e7d4427825 # v0.19.0 https://github.com/babylonlabs-io/.github/releases/tag/v0.19.0
    needs: ["test"]
    secrets: inherit
    with:
     publish: false
     dockerfile: ./contrib/images/local-bcd/Dockerfile
     repoName: babylon-sdk
