name: ci

on:
  push:
    branches:
    - '**'

jobs:
  test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@v0.11.2
    with:
     run-unit-tests: true
     run-integration-tests: true
     integration-tests-command: |
      make test-integration
     
  docker_pipeline:
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@v0.11.2
    needs: ["test"]
    secrets: inherit
    with:
     publish: false
     dockerfile: ./contrib/images/local-bcd/Dockerfile
     repoName: babylon-sdk
