name: e2e
on:
  push:
    branches:
    - '**'

concurrency:
  group: e2e-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  e2e-docker-build-ibcsim:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build docker ibcsim-bcd
        run: |
          make build-ibcsim-bcd
      - name: Docker save ibcsim
        run: |
          docker save -o /tmp/docker-ibcsim.tar.gz babylonlabs-io/ibcsim-bcd:latest
      - name: Upload ibcsim artifact
        uses: actions/upload-artifact@v4
        with:
          name: ibcsim-${{ github.sha }}
          path: /tmp/docker-ibcsim.tar.gz

  e2e-docker-build-babylond:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build docker babylond
        run: |
          make build-babylond
      - name: Docker save babylond
        run: |
          docker save -o /tmp/docker-babylond.tar.gz babylonlabs-io/babylond:latest
      - name: Upload babylond artifact
        uses: actions/upload-artifact@v4
        with:
          name: babylond-${{ github.sha }}
          path: /tmp/docker-babylond.tar.gz

# TODO: re-enable e2e when issues are fixed
#  e2e-test:
#    needs: [e2e-docker-build-ibcsim, e2e-docker-build-babylond]
#    runs-on: ubuntu-22.04
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#      - name: Download ibcsim artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: ibcsim-${{ github.sha }}
#          path: /tmp
#      - name: Download babylond artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: babylond-${{ github.sha }}
#          path: /tmp
#      - name: Docker load ibcsim
#        run: |
#          docker load < /tmp/docker-ibcsim.tar.gz
#      - name: Docker load babylond
#        run: |
#          docker load < /tmp/docker-babylond.tar.gz
#      - name: Cache Go
#        uses: actions/setup-go@v5
#        with:
#          go-version: 1.23
#      - name: Run E2E Tests
#        run: sudo make test-e2e-cache
