name: integration-e2e

on:
  push:
    branches:
    - '**'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build IBC Simulator BCD Image
        run: make build-ibcsim-bcd

      - name: Build Babylond Image
        run: make build-babylond

      - name: Cache Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Run Integration Tests
        run: make test-e2e-bcd-consumer-integration
