name: docker_publish

on:
  push:
    branches:
    - 'main'
    - 'dev'
    tags:
    - '*'
  
jobs:
  lint_test:
    uses: babylonchain/.github/.github/workflows/reusable_go_lint_test.yml@v0.1.0
    with:
      run-unit-tests: true
      run-integration-tests: true
      run-lint: false
      integration-tests-command: |
        make test-e2e
      
  docker_pipeline:
    uses: babylonchain/.github/.github/workflows/reusable_docker_pipeline.yml@v0.1.0
    needs: ["lint_test"]
    secrets: inherit
    with:
      publish: true
      dockerfile: ./Dockerfile
      repoName: babylon-sdk