name: docker_publish

on:
  push:
    branches:
    - 'main'
    - 'dev'
    tags:
    - '*'
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@v0.11.2
    with:
      run-unit-tests: true
      
  docker_pipeline:
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@v0.11.2
    needs: ["test"]
    secrets: inherit
    with:
      publish: true
      dockerfile: ./contrib/images/local-bcd/Dockerfile
      repoName: babylon-sdk
