name: docker_publish

on:
  push:
    branches:
    - 'main'
    - 'dev'
    tags:
    - '*'
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@5d014a155c08d56a1b5673d049f2b4e7d4427825 # v0.19.0 https://github.com/babylonlabs-io/.github/releases/tag/v0.19.0
    with:
      run-unit-tests: true
      
  docker_pipeline:
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@5d014a155c08d56a1b5673d049f2b4e7d4427825 # v0.19.0 https://github.com/babylonlabs-io/.github/releases/tag/v0.19.0
    needs: ["test"]
    secrets: inherit
    with:
      publish: true
      dockerfile: ./contrib/images/local-bcd/Dockerfile
      repoName: babylon-sdk
